export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EXCHANGE = 'CHANGE_EXCHANGE';
export const CHANGE_INFO = 'CHANGE_INFO';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SAVE_EXPENSE_EDIT = 'SAVE_EXPENSE_EDIT';
